spring.application.name=Usuario

# Data Source Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuario
spring.datasource.username=postgres
spring.datasource.password=Gui250312
spring.datasource.driver-class-name=org.postgresql.Driver